scrape_configs:
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:9100
  - job_name: "docker"
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:9323
